"""Added username column to User

Revision ID: d6d9f173108a
Revises: 0088ecbde7b6
Create Date: 2024-02-09 15:40:58.107350

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6d9f173108a'
down_revision = '0088ecbde7b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(length=64), nullable=False))
        batch_op.drop_index('ix_user_user')
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)
        batch_op.drop_column('user')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user', sa.VARCHAR(length=64), nullable=False))
        batch_op.drop_index(batch_op.f('ix_user_username'))
        batch_op.create_index('ix_user_user', ['user'], unique=1)
        batch_op.drop_column('username')

    # ### end Alembic commands ###
